name: README CI

on:
  push:
    branches:
      - "**"
    paths:
      - "**.md"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail

      - name: Upload artifact(s)
        uses: actions/upload-artifact@v3
        with:
          name: markdown-lint-report
          path: public/
